### ISSUE TITLE
Improve tracking of local variables in codegen

### ISSUE THREAD

**Issue by RGates94** [OffchainLabs/arb-os#147]
Currently, codegen for individual statements must track the total number of locals slots needed in the outer scope, and return the total number of locals slots in needs including the previous bindings.  This can make the logic somewhat complicated and error prone.

One alternative approach would be to have statements only track the number of slots needed for statement scope locals, and return that along with the list of outer scope bindings, potentially using a struct to automatically track active variables.

In addition, there is potential for optimization by reusing locals slots for function scope locals with disjoint lifetimes.

**Comment by rachel-bousfield** [comment]
Solved by
- #608
