### ISSUE TITLE
Add Mini operator to delete item from a map

### ISSUE THREAD

**Issue by edfelten** [OffchainLabs/arb-os#247]
Currently, Mini doesn't have a graceful method to delete an item from a map.  For example, to delete an item from a map<address, uint>, you have to write something like this:

> import core::kvs::Kvs;
> import core::kvs::builtin_kvsDelete;
> 
>      unsafecast<map<address, uint>>(builtin_kvsDelete(unsafecast<Kvs>(theMap), uint(addr)));

It would be better to have a statement like `delete(m, a)` with proper type checking.

**Comment by RachelFranks** [comment]
Addressed in PR #568

**Comment by rachel-bousfield** [comment]
Solved in both
- #612 
- #568

Though generics alone gives you this
