### ISSUE TITLE
File evmlogs.mini should be evmLogs.mini

### ISSUE THREAD

**Issue by tstewart-writer** [OffchainLabs/arb-os#258]
I tried to build this arb-os on Lubuntu 20.04, but got a compilation error.
```
Compilation error: Can not open arb_os/evmLogs.mini: Os { code: 2, kind: NotFound, message: "No such file or directory" },
 No location
In file: Unknown
Error: CompileError { description: "Can not open arb_os/evmLogs.mini: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }", location: None }
make: *** [Makefile:55: arb_os/arbos.mexe] Error 1
```
I noticed that there was no file emvLogs.mini, instead it is emvlogs.mini. I was able to compile/test properly when I renamed it evmLogs.mini. This is probably because Linux is case sensitive.

**Comment by RGates94** [comment]
Thanks for the report, this was fixed by #267.  We kept the lowercase in the file name but the import now correctly matches the case.
