### ISSUE TITLE
Improve line number reporting for errors

### ISSUE THREAD

**Issue by edfelten** [OffchainLabs/arb-os#4]
Two problems with line number reporting for errors.
(1) Line number is often off-by-one, probably because we need to be smarter about how we use the line number markers in the grammar file.  Or possibly because line numbers are zero-indexed in the underlying data structure.
(2) The line number often should be accompanied by a file name. This is conceptually simple to do but the obvious approach to doing it makes the Rust borrow checker angry.

**Comment by RGates94** [comment]
This was resolved a number of months ago, I lost track of the specific PRs that did it.
