### ISSUE TITLE
Separate Mini-Compiler and ArbOs into separate respositories

### ISSUE THREAD

**Issue by RGates94** [OffchainLabs/arb-os#432]
As ArbOs and the Mini compiler have largely separate functionalities and the Mini compiler functions mostly separately from ArbOs, it would provide organizational benefits to separate these into different repositories, and add the Mini Compiler as a submodule of ArbOs.  This depends on resolution of #431

**Comment by rachel-bousfield** [comment]
We researched this but decided the refactor wouldn't be worth it
