### ISSUE TITLE
Allow creation of length one tuples

### ISSUE THREAD

**Issue by RGates94** [OffchainLabs/arb-os#435]
Currently tuple types of length one get coerced to their inner value.  This can create problems when you wish to distinguish between the tuple and the inner type, or want a specific representation in AVM.  This should be changed so that one length tuples are allowed.

**Comment by rachel-bousfield** [comment]
The grammar supports length one tuples so long as a `,` is used
```rs
let a = (32,)          // a tuple with the value 32 inside it
let a = (32)           // the value 32
```
