### ISSUE TITLE
Add mixed let statement

### ISSUE THREAD

**Issue by RGates94** [OffchainLabs/arb-os#491]
It would be beneficial to have a mixed let statement, that assigns some fields of a match pattern to new variables, and others to existing variables.  One possible syntax for this would be:

```
func main() {
    let y = 4;
    (let x, y) = f(y);
}

func f(y: uint) {
    return (y, y+1);
}
```
This would allow the use of fewer local variables for the same logic, saving gas.

**Comment by edfelten** [comment]
The main benefit of this is safety.  With the current syntax we often have to use a construction like this:

let (updatedStream, value) = bytestream_getByte(stream);
stream = updatedStream;

It's easy to forget the second line, and end up using the wrong value of stream in the ensuing code.  The proposed syntax would let the programmer say what they mean, without needing to introduce the error-prone temporary variable.

**Comment by edfelten** [comment]
I agree that we shouldn't be worrying about gas costs in designing this. Better for the code be clear and have the compiler worry about that sort of optimization.

**Comment by RGates94** [comment]
I ended up rushing the wording a bit because I was a bit surprised by the start of the standup meeting while writing this, I fully agree with the statements above.
