### ISSUE TITLE
Method name_from_id on StringTable should return an option

### ISSUE THREAD

**Issue by RGates94** [OffchainLabs/arb-os#555]
Currently `name_from_id` uses indexing, and therefore will panic if passed an invalid ID, we should instead use the `get` method and return an option.

**Comment by RachelFranks** [comment]
Since ids are never removed from a string table, and the only way to get a string id is to retrieve it from the table, I don't think there should ever be a time that an invalid StringID is passed to the `name_from_id` method.

**Comment by RGates94** [comment]
As ids are simply aliases to `usize`s, and are stored in various places in the AST, it would be very possible to pass either a `usize` that does not originate from the string table, or an id that originates from a string table in another module.
