### ISSUE TITLE
Linker should type check function imports

### ISSUE THREAD

**Issue by edfelten** [OffchainLabs/arb-os#6]
Currently the linker doesn't verify that the type declaration for a function in an import statement matches the actually implementation that is linked to it. We should fix this.

We might want to just require that the import declaration be a subtype of the implementation. 

We might also want to allow unsafe casting of function types in an import, in order to allow hackish quasi-generic functionality.  Although some simple form of true generics seems easier.

**Comment by RGates94** [comment]
This is made obsolete with the removal of imported types #310.
