### ISSUE TITLE
Support versioning of EVM code parsing

### ISSUE THREAD

**Issue by edfelten** [OffchainLabs/arb-os#606]
Our EVM code parsing algorithm will probably change over time, as the EVM code format standard evolves. To support this, we should version the parsing algorithm and label each contract (and cached compilation result) with the parsing version that was active at the time it was deployed. That will allow us to avoid (1) reparsing later under a different algorithm, and (2) getting a wrong result from the compilation result cache due to changes in the caching algorithm.

This will start to matter when EIPs that change code parsing (more significantly than it has already changed) start to get deployed.

**Comment by Lldenaurois** [comment]
This looks like it might be up my alley. May I be assigned to this issue?

**Comment by edfelten** [comment]
Thanks for asking!  This one is already being addressed in PR #615 .  Apologies for not linking it to the PR previously.
